// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpfEvent struct {
	_       structs.HostLayout
	Kind    uint32
	SrcMac  [6]uint8
	DstMac  [6]uint8
	SrcIp   uint32
	DstIp   uint32
	SrcPort uint16
	DstPort uint16
	State   uint8
	_       [3]byte
}

type bpfServerConfig struct {
	_    structs.HostLayout
	Ip   uint32
	Port uint16
	Mac  [6]uint8
}

type bpfSession struct {
	_           structs.HostLayout
	ClientIp    uint32
	ClientPort  uint16
	_           [2]byte
	ServerIp    uint32
	ServerPort  uint16
	Reserve     uint8
	Used        uint8
	LbPort      uint16
	ClientMac   [6]uint8
	ServerMac   [6]uint8
	ClientState uint8
	ServerState uint8
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	XdpMain *ebpf.ProgramSpec `ebpf:"xdp_main"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	Events     *ebpf.MapSpec `ebpf:"events"`
	Servers    *ebpf.MapSpec `ebpf:"servers"`
	SessionMap *ebpf.MapSpec `ebpf:"session_map"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
	LoadBalancerIp  *ebpf.VariableSpec `ebpf:"load_balancer_ip"`
	LoadBalancerMac *ebpf.VariableSpec `ebpf:"load_balancer_mac"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	Events     *ebpf.Map `ebpf:"events"`
	Servers    *ebpf.Map `ebpf:"servers"`
	SessionMap *ebpf.Map `ebpf:"session_map"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.Events,
		m.Servers,
		m.SessionMap,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
	LoadBalancerIp  *ebpf.Variable `ebpf:"load_balancer_ip"`
	LoadBalancerMac *ebpf.Variable `ebpf:"load_balancer_mac"`
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	XdpMain *ebpf.Program `ebpf:"xdp_main"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.XdpMain,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfel.o
var _BpfBytes []byte
